from gpt3_assistant.exceptions.speech_recognition_error import SpeechRecognitionError


class SpeechRecognitionRequestError(SpeechRecognitionError):
    pass
